package com.lcwd.rating.entities;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

@Getter
@Setter
@AllArgsConstructor
@NoArgsConstructor
@Document("user_ratings")   // in mongoDB we have to write @Document to tell spring boot that we have a entity named Rating
public class Rating {
    @Id // primary key in mongoDb and it will be autogenerated in mongodb
    private String ratingId;
    private String userId;  // this info we will be receiving from user microservice
    private String hotelId;
    private int rating;
    private String feedback;
}
