
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

server:
  port: 8082

# eureka client configuration
eureka:
  client:
    fetch-registry: true  # by default these are true
    register-with-eureka: true  # get registered with eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka # it will use this eureka ser url inorder to register with server
  instance:
    prefer-ip-address: true # it will prefer ip address whenever it sees the server#

