server:
  port: 8081
# database configuration of mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Vishal@123
    driver-class-name: com.mysql.cj.jdbc.Driver
  # configuration of spring jpa
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  application:
    name: USER-SERVICE  # this will provide name of application

# eureka configuration
eureka:
  client:
    fetch-registry: true  # by default these are true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka # it will use this eureka server url inorder to register with server
  instance:
    prefer-ip-address: true # it will prefer ip address